### ISSUE TITLE
500 Error on /admin – User invalid

### ISSUE THREAD

**Issue by garethrees** [mysociety/derechoapreguntar-theme#142]
> Dear Garteh reviewing options see admin does not work then you can check the Summary, please

```
An ActiveRecord::RecordInvalid occurred in admin_general#index:

La validación falló: Terms Por favor, acepte los Términos y Condiciones, Identity card number Por favor, introduzca su número de cedula de identidad, General law Introduzca su información de Ley General
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/validations.rb:56:in `save!'

-------------------------------
Backtrace:
-------------------------------

vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/validations.rb:56:in `save!'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/transactions.rb:264:in `save!'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/transactions.rb:313:in `with_transaction_returning_status'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/transactions.rb:264:in `save!'
app/models/user.rb:109:in `internal_admin_user'
app/models/info_request.rb:534:in `holding_pen_request'
app/controllers/admin_general_controller.rb:30:in `index'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:167:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/rendering.rb:10:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:18:in `process_action'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:569:in `_run__482196654__process_action__1715301439__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:215:in `_conditional_callback_around_1115'
app/controllers/application_controller.rb:106:in `record_memory'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1115'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:557:in `_run__482196654__process_action__1715301439__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:17:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/rescue.rb:29:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:23:in `process_action'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:353:in `perform_action_with_newrelic_trace'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:22:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:121:in `process'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:45:in `process'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal.rb:203:in `dispatch'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal.rb:246:in `action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:36:in `call'
vendor/bundle/ruby/1.8/gems/journey-1.0.4/lib/journey/router.rb:68:in `call'
vendor/bundle/ruby/1.8/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
vendor/bundle/ruby/1.8/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:608:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/exception_notification-3.0.1/lib/exception_notifier.rb:41:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/head.rb:14:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/flash.rb:242:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/cookies.rb:341:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
lib/whatdotheyknow/strip_empty_sessions.rb:14:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:64:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:28:in `call'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `_run__592277964__call__4__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/rack/logger.rb:32:in `call_app'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `call'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/tagged_logging.rb:22:in `tagged'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/request_id.rb:22:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/static.rb:83:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/engine.rb:484:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/application.rb:231:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `send'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:449:in `initialize'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:449:in `new'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:449:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `times'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:447:in `synchronize'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:447:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:208:in `main_loop'
/usr/share/passenger/helper-scripts/rack-loader.rb:133
```

**Comment by garethrees** [comment]
The app could not create `User.internal_admin_user` since the code in Alaveteli core generated an invalid user instance for this theme. Patched the method in 1319f5146.
